const mockResidentes = [
  {
    id_residente: 1,
    primeiro_nome: "Ana",
    sobrenome: "Silva",
    data_nascimento: "2005-03-10",
    sexo: "feminino",
  },
  {
    id_residente: 2,
    primeiro_nome: "Bruno",
    sobrenome: "Costa",
    data_nascimento: "2002-11-20",
    sexo: "masculino",
  },
  {
    id_residente: 3,
    primeiro_nome: "Carla",
    sobrenome: "Mendes",
    data_nascimento: "1999-07-01",
    sexo: "feminino",
  },
  {
    id_residente: 4,
    primeiro_nome: "Diogo",
    sobrenome: "Alves",
    data_nascimento: "2008-01-15",
    sexo: "masculino",
  },
  {
    id_residente: 5,
    primeiro_nome: "Elisa",
    sobrenome: "Fernandes",
    data_nascimento: "2003-05-30",
    sexo: "feminino",
  },
  {
    id_residente: 6,
    primeiro_nome: "Fábio",
    sobrenome: "Gomes",
    data_nascimento: "2001-09-05",
    sexo: "masculino",
  },
  {
    id_residente: 7,
    primeiro_nome: "Gabriela",
    sobrenome: "Lima",
    data_nascimento: "2006-02-12",
    sexo: "feminino",
  },
  {
    id_residente: 8,
    primeiro_nome: "Hugo",
    sobrenome: "Nunes",
    data_nascimento: "2000-12-25",
    sexo: "masculino",
  },
  {
    id_residente: 9,
    primeiro_nome: "Isabela",
    sobrenome: "Ribeiro",
    data_nascimento: "2007-08-19",
    sexo: "feminino",
  },
  {
    id_residente: 10,
    primeiro_nome: "João",
    sobrenome: "Santos",
    data_nascimento: "2004-04-03",
    sexo: "masculino",
  },
  {
    id_residente: 11,
    primeiro_nome: "Laura",
    sobrenome: "Almeida",
    data_nascimento: "2002-06-18",
    sexo: "feminino",
  },
  {
    id_residente: 12,
    primeiro_nome: "Miguel",
    sobrenome: "Barbosa",
    data_nascimento: "2004-10-30",
    sexo: "masculino",
  },
  {
    id_residente: 13,
    primeiro_nome: "Natália",
    sobrenome: "Carvalho",
    data_nascimento: "2001-03-22",
    sexo: "feminino",
  },
  {
    id_residente: 14,
    primeiro_nome: "Otávio",
    sobrenome: "Dias",
    data_nascimento: "2006-07-14",
    sexo: "masculino",
  },
  {
    id_residente: 15,
    primeiro_nome: "Paula",
    sobrenome: "Ferreira",
    data_nascimento: "2000-12-05",
    sexo: "feminino",
  },
  {
    id_residente: 16,
    primeiro_nome: "Rafael",
    sobrenome: "Gusmão",
    data_nascimento: "2003-08-27",
    sexo: "masculino",
  },
  {
    id_residente: 17,
    primeiro_nome: "Sandra",
    sobrenome: "Henriques",
    data_nascimento: "2005-01-09",
    sexo: "feminino",
  },
  {
    id_residente: 18,
    primeiro_nome: "Thiago",
    sobrenome: "Lopes",
    data_nascimento: "2007-04-21",
    sexo: "masculino",
  },
  {
    id_residente: 19,
    primeiro_nome: "Úrsula",
    sobrenome: "Moreira",
    data_nascimento: "2001-11-11",
    sexo: "feminino",
  },
  {
    id_residente: 20,
    primeiro_nome: "Victor",
    sobrenome: "Nogueira",
    data_nascimento: "2004-02-23",
    sexo: "masculino",
  },
];

const mockFuncionarios = [
  {
    id_funcionario: 101,
    numero_registro: "A101",
    primeiro_nome: "Marcos",
    sobrenome: "Oliveira",
    turno: "manha",
    status: "ativo",
  },
  {
    id_funcionario: 102,
    numero_registro: "A102",
    primeiro_nome: "Lúcia",
    sobrenome: "Pereira",
    turno: "tarde",
    status: "ativo",
  },
  {
    id_funcionario: 103,
    numero_registro: "A103",
    primeiro_nome: "Ricardo",
    sobrenome: "Abreu",
    turno: "noite",
    status: "ativo",
  },
  {
    id_funcionario: 104,
    numero_registro: "B101",
    primeiro_nome: "Sofia",
    sobrenome: "Martins",
    turno: "manha",
    status: "inativo",
  },
  {
    id_funcionario: 105,
    numero_registro: "B102",
    primeiro_nome: "Tiago",
    sobrenome: "Cardoso",
    turno: "tarde",
    status: "ativo",
  },
  {
    id_funcionario: 106,
    numero_registro: "B103",
    primeiro_nome: "Vanessa",
    sobrenome: "Rocha",
    turno: "noite",
    status: "ativo",
  },
  {
    id_funcionario: 107,
    numero_registro: "C101",
    primeiro_nome: "André",
    sobrenome: "Barbosa",
    turno: "manha",
    status: "ativo",
  },
  {
    id_funcionario: 108,
    numero_registro: "C102",
    primeiro_nome: "Beatriz",
    sobrenome: "Freitas",
    turno: "tarde",
    status: "ativo",
  },
  {
    id_funcionario: 109,
    numero_registro: "C103",
    primeiro_nome: "Cauã",
    sobrenome: "Dias",
    turno: "noite",
    status: "inativo",
  },
  {
    id_funcionario: 110,
    numero_registro: "D101",
    primeiro_nome: "Daniela",
    sobrenome: "Pinto",
    turno: "manha",
    status: "ativo",
  },
  {
    id_funcionario: 111,
    numero_registro: "E101",
    primeiro_nome: "Eduardo",
    sobrenome: "Queiroz",
    turno: "tarde",
    status: "ativo",
  },
  {
    id_funcionario: 112,
    numero_registro: "E102",
    primeiro_nome: "Fernanda",
    sobrenome: "Souza",
    turno: "noite",
    status: "ativo",
  },
  {
    id_funcionario: 113,
    numero_registro: "E103",
    primeiro_nome: "Gustavo",
    sobrenome: "Teixeira",
    turno: "manha",
    status: "ativo",
  },
  {
    id_funcionario: 114,
    numero_registro: "F101",
    primeiro_nome: "Helena",
    sobrenome: "Vieira",
    turno: "tarde",
    status: "inativo",
  },
  {
    id_funcionario: 115,
    numero_registro: "F102",
    primeiro_nome: "Igor",
    sobrenome: "Xavier",
    turno: "noite",
    status: "ativo",
  },
  {
    id_funcionario: 116,
    numero_registro: "F103",
    primeiro_nome: "Juliana",
    sobrenome: "Zanetti",
    turno: "manha",
    status: "ativo",
  },
  {
    id_funcionario: 117,
    numero_registro: "G101",
    primeiro_nome: "Kleber",
    sobrenome: "Arruda",
    turno: "tarde",
    status: "ativo",
  },
  {
    id_funcionario: 118,
    numero_registro: "G102",
    primeiro_nome: "Larissa",
    sobrenome: "Borges",
    turno: "noite",
    status: "ativo",
  },
  {
    id_funcionario: 119,
    numero_registro: "G103",
    primeiro_nome: "Marcelo",
    sobrenome: "Campos",
    turno: "manha",
    status: "inativo",
  },
  {
    id_funcionario: 120,
    numero_registro: "H101",
    primeiro_nome: "Nicole",
    sobrenome: "Dantas",
    turno: "tarde",
    status: "ativo",
  },
];

const mockMedicamentos = [
  {
    id: 1,
    horario: "08:00",
    residenteNome: "Ana Silva",
    medicamento: "Paracetamol",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 2,
    horario: "08:00",
    residenteNome: "Bruno Costa",
    medicamento: "Dipirona",
    dosagem: "20 gotas",
    tipo: "Gotas",
  },
  {
    id: 3,
    horario: "09:00",
    residenteNome: "Carla Mendes",
    medicamento: "Amoxicilina",
    dosagem: "5ml",
    tipo: "Líquido",
  },
  {
    id: 4,
    horario: "10:00",
    residenteNome: "Diogo Alves",
    medicamento: "Ibuprofeno",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 5,
    horario: "12:00",
    residenteNome: "Elisa Fernandes",
    medicamento: "Loratadina",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 6,
    horario: "14:00",
    residenteNome: "Fábio Gomes",
    medicamento: "Dipirona",
    dosagem: "20 gotas",
    tipo: "Gotas",
  },
  {
    id: 7,
    horario: "16:00",
    residenteNome: "Gabriela Lima",
    medicamento: "Paracetamol",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 8,
    horario: "18:00",
    residenteNome: "Hugo Nunes",
    medicamento: "Omeprazol",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 9,
    horario: "20:00",
    residenteNome: "Isabela Ribeiro",
    medicamento: "Amoxicilina",
    dosagem: "5ml",
    tipo: "Líquido",
  },
  {
    id: 10,
    horario: "22:00",
    residenteNome: "João Santos",
    medicamento: "Ibuprofeno",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 11,
    horario: "08:00",
    residenteNome: "Laura Almeida",
    medicamento: "Sinvastatina",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 12,
    horario: "08:00",
    residenteNome: "Miguel Barbosa",
    medicamento: "Losartana",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 13,
    horario: "09:00",
    residenteNome: "Natália Carvalho",
    medicamento: "Metformina",
    dosagem: "2 comp.",
    tipo: "Comprimido",
  },
  {
    id: 14,
    horario: "10:00",
    residenteNome: "Otávio Dias",
    medicamento: "AAS",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 15,
    horario: "12:00",
    residenteNome: "Paula Ferreira",
    medicamento: "Gliclazida",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 16,
    horario: "14:00",
    residenteNome: "Rafael Gusmão",
    medicamento: "Losartana",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 17,
    horario: "16:00",
    residenteNome: "Sandra Henriques",
    medicamento: "Sinvastatina",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 18,
    horario: "18:00",
    residenteNome: "Thiago Lopes",
    medicamento: "Paracetamol",
    dosagem: "30 gotas",
    tipo: "Gotas",
  },
  {
    id: 19,
    horario: "20:00",
    residenteNome: "Úrsula Moreira",
    medicamento: "Metformina",
    dosagem: "2 comp.",
    tipo: "Comprimido",
  },
  {
    id: 20,
    horario: "22:00",
    residenteNome: "Victor Nogueira",
    medicamento: "AAS",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
];

const mockAtividades = [
  {
    id: 1,
    data: "2025-11-16T10:00:00Z",
    horario: "10:00:00",
    nome_atividade: "Pintura em Tela",
    duracao: "1 hora",
    status: "Agendada",
    participantes_nomes: "Ana Silva, Bruno Costa",
  },
  {
    id: 2,
    data: "2025-11-16T15:00:00Z",
    horario: "15:00:00",
    nome_atividade: "Fisioterapia em Grupo",
    duracao: "45 minutos",
    status: "Agendada",
    participantes_nomes: "Carla Mendes, Diogo Alves",
  },
  {
    id: 3,
    data: "2025-11-17T09:00:00Z",
    horario: "09:00:00",
    nome_atividade: "Aula de Música",
    duracao: "1 hora",
    status: "Agendada",
    participantes_nomes: "Elisa Fernandes, Fábio Gomes",
  },
  {
    id: 4,
    data: "2025-11-17T14:00:00Z",
    horario: "14:00:00",
    nome_atividade: "Leitura Coletiva",
    duracao: "1 hora",
    status: "Concluída",
    participantes_nomes: "Gabriela Lima",
  },
  {
    id: 5,
    data: "2025-11-18T10:00:00Z",
    horario: "10:00:00",
    nome_atividade: "Jardinagem",
    duracao: "1 hora",
    status: "Agendada",
    participantes_nomes: "Hugo Nunes, Isabela Ribeiro",
  },
  {
    id: 6,
    data: "2025-11-18T16:00:00Z",
    horario: "16:00:00",
    nome_atividade: "Sessão de Cinema",
    duracao: "2 horas",
    status: "Agendada",
    participantes_nomes: "João Santos, Ana Silva",
  },
  {
    id: 7,
    data: "2025-11-19T11:00:00Z",
    horario: "11:00:00",
    nome_atividade: "Alongamento",
    duracao: "30 minutos",
    status: "Cancelada",
    participantes_nomes: "Bruno Costa",
  },
  {
    id: 8,
    data: "2025-11-19T15:00:00Z",
    horario: "15:00:00",
    nome_atividade: "Oficina de Culinária",
    duracao: "1 hora",
    status: "Agendada",
    participantes_nomes: "Carla Mendes, Elisa Fernandes",
  },
  {
    id: 9,
    data: "2025-11-20T09:00:00Z",
    horario: "09:00:00",
    nome_atividade: "Jogo de Tabuleiro",
    duracao: "1 hora",
    status: "Agendada",
    participantes_nomes: "Diogo Alves, Fábio Gomes",
  },
  {
    id: 10,
    data: "2025-11-20T14:00:00Z",
    horario: "14:00:00",
    nome_atividade: "Conversa Terapêutica",
    duracao: "1 hora",
    status: "Agendada",
    participantes_nomes: "Gabriela Lima, Hugo Nunes",
  },
  {
    id: 11,
    data: "2025-11-21T10:00:00Z",
    horario: "10:00:00",
    nome_atividade: "Caminhada Leve",
    duracao: "40 minutos",
    status: "Agendada",
    participantes_nomes: "Laura Almeida, Miguel Barbosa",
  },
  {
    id: 12,
    data: "2025-11-21T15:00:00Z",
    horario: "15:00:00",
    nome_atividade: "Yoga",
    duracao: "1 hora",
    status: "Agendada",
    participantes_nomes: "Natália Carvalho, Otávio Dias",
  },
  {
    id: 13,
    data: "2025-11-22T09:00:00Z",
    horario: "09:00:00",
    nome_atividade: "Hidroginástica",
    duracao: "50 minutos",
    status: "Agendada",
    participantes_nomes: "Paula Ferreira, Rafael Gusmão",
  },
  {
    id: 14,
    data: "2025-11-22T14:00:00Z",
    horario: "14:00:00",
    nome_atividade: "Artesanato",
    duracao: "1 hora",
    status: "Concluída",
    participantes_nomes: "Sandra Henriques",
  },
  {
    id: 15,
    data: "2025-11-23T10:00:00Z",
    horario: "10:00:00",
    nome_atividade: "Visita ao Museu (Virtual)",
    duracao: "1 hora",
    status: "Agendada",
    participantes_nomes: "Thiago Lopes, Úrsula Moreira",
  },
  {
    id: 16,
    data: "2025-11-23T16:00:00Z",
    horario: "16:00:00",
    nome_atividade: "Bingo",
    duracao: "1.5 horas",
    status: "Agendada",
    participantes_nomes: "Victor Nogueira, Laura Almeida",
  },
  {
    id: 17,
    data: "2025-11-24T11:00:00Z",
    horario: "11:00:00",
    nome_atividade: "Dança Sênior",
    duracao: "1 hora",
    status: "Cancelada",
    participantes_nomes: "Miguel Barbosa",
  },
  {
    id: 18,
    data: "2025-11-24T15:00:00Z",
    horario: "15:00:00",
    nome_atividade: "Palestra Nutricional",
    duracao: "1 hora",
    status: "Agendada",
    participantes_nomes: "Natália Carvalho, Paula Ferreira",
  },
  {
    id: 19,
    data: "2025-11-25T09:00:00Z",
    horario: "09:00:00",
    nome_atividade: "Meditação Guiada",
    duracao: "30 minutos",
    status: "Agendada",
    participantes_nomes: "Otávio Dias, Rafael Gusmão",
  },
  {
    id: 20,
    data: "2025-11-25T14:00:00Z",
    horario: "14:00:00",
    nome_atividade: "Tarde de Histórias",
    duracao: "1 hora",
    status: "Agendada",
    participantes_nomes: "Sandra Henriques, Thiago Lopes",
  },
];

const mockRelatorios = [
  {
    id: 1,
    data: "2025-11-16T00:00:00Z",
    residenteNome: "Ana Silva",
    medicamento: "Paracetamol",
    responsavelNome: "Marcos Oliveira",
    statusMedicacao: "Medicado",
  },
  {
    id: 2,
    data: "2025-11-16T00:00:00Z",
    residenteNome: "Bruno Costa",
    medicamento: "Dipirona",
    responsavelNome: "Lúcia Pereira",
    statusMedicacao: "Medicado",
  },
  {
    id: 3,
    data: "2025-11-15T00:00:00Z",
    residenteNome: "Carla Mendes",
    medicamento: "Amoxicilina",
    responsavelNome: "Ricardo Abreu",
    statusMedicacao: "Não Tomado",
  },
  {
    id: 4,
    data: "2025-11-15T00:00:00Z",
    residenteNome: "Diogo Alves",
    medicamento: "Ibuprofeno",
    responsavelNome: "Sofia Martins",
    statusMedicacao: "Medicado",
  },
  {
    id: 5,
    data: "2025-11-14T00:00:00Z",
    residenteNome: "Elisa Fernandes",
    medicamento: "Loratadina",
    responsavelNome: "Tiago Cardoso",
    statusMedicacao: "Medicado",
  },
  {
    id: 6,
    data: "2025-11-14T00:00:00Z",
    residenteNome: "Fábio Gomes",
    medicamento: "Dipirona",
    responsavelNome: "Vanessa Rocha",
    statusMedicacao: "N/A",
  },
  {
    id: 7,
    data: "2025-11-13T00:00:00Z",
    residenteNome: "Gabriela Lima",
    medicamento: "Paracetamol",
    responsavelNome: "André Barbosa",
    statusMedicacao: "Medicado",
  },
  {
    id: 8,
    data: "2025-11-13T00:00:00Z",
    residenteNome: "Hugo Nunes",
    medicamento: "Omeprazol",
    responsavelNome: "Beatriz Freitas",
    statusMedicacao: "Medicado",
  },
  {
    id: 9,
    data: "2025-11-12T00:00:00Z",
    residenteNome: "Isabela Ribeiro",
    medicamento: "Amoxicilina",
    responsavelNome: "Cauã Dias",
    statusMedicacao: "Medicado",
  },
  {
    id: 10,
    data: "2025-11-12T00:00:00Z",
    residenteNome: "João Santos",
    medicamento: "Ibuprofeno",
    responsavelNome: "Daniela Pinto",
    statusMedicacao: "Não Tomado",
  },
  {
    id: 11,
    data: "2025-11-11T00:00:00Z",
    residenteNome: "Laura Almeida",
    medicamento: "Sinvastatina",
    responsavelNome: "Eduardo Queiroz",
    statusMedicacao: "Medicado",
  },
  {
    id: 12,
    data: "2025-11-11T00:00:00Z",
    residenteNome: "Miguel Barbosa",
    medicamento: "Losartana",
    responsavelNome: "Fernanda Souza",
    statusMedicacao: "Medicado",
  },
  {
    id: 13,
    data: "2025-11-10T00:00:00Z",
    residenteNome: "Natália Carvalho",
    medicamento: "Metformina",
    responsavelNome: "Gustavo Teixeira",
    statusMedicacao: "Não Tomado",
  },
  {
    id: 14,
    data: "2025-11-10T00:00:00Z",
    residenteNome: "Otávio Dias",
    medicamento: "AAS",
    responsavelNome: "Helena Vieira",
    statusMedicacao: "Medicado",
  },
  {
    id: 15,
    data: "2025-11-09T00:00:00Z",
    residenteNome: "Paula Ferreira",
    medicamento: "Gliclazida",
    responsavelNome: "Igor Xavier",
    statusMedicacao: "Medicado",
  },
  {
    id: 16,
    data: "2025-11-09T00:00:00Z",
    residenteNome: "Rafael Gusmão",
    medicamento: "Losartana",
    responsavelNome: "Juliana Zanetti",
    statusMedicacao: "N/A",
  },
  {
    id: 17,
    data: "2025-11-08T00:00:00Z",
    residenteNome: "Sandra Henriques",
    medicamento: "Sinvastatina",
    responsavelNome: "Kleber Arruda",
    statusMedicacao: "Medicado",
  },
  {
    id: 18,
    data: "2025-11-08T00:00:00Z",
    residenteNome: "Thiago Lopes",
    medicamento: "Paracetamol",
    responsavelNome: "Larissa Borges",
    statusMedicacao: "Medicado",
  },
  {
    id: 19,
    data: "2025-11-07T00:00:00Z",
    residenteNome: "Úrsula Moreira",
    medicamento: "Metformina",
    responsavelNome: "Marcelo Campos",
    statusMedicacao: "Medicado",
  },
  {
    id: 20,
    data: "2025-11-07T00:00:00Z",
    residenteNome: "Victor Nogueira",
    medicamento: "AAS",
    responsavelNome: "Nicole Dantas",
    statusMedicacao: "Não Tomado",
  },
];
