const mockResidentes = [
  {
    id_residente: 1,
    primeiro_nome: "Ana",
    sobrenome: "Silva",
    data_nascimento: "2005-03-10",
    sexo: "feminino",
  },
  {
    id_residente: 2,
    primeiro_nome: "Bruno",
    sobrenome: "Costa",
    data_nascimento: "2002-11-20",
    sexo: "masculino",
  },
  {
    id_residente: 3,
    primeiro_nome: "Carla",
    sobrenome: "Mendes",
    data_nascimento: "1999-07-01",
    sexo: "feminino",
  },
  {
    id_residente: 4,
    primeiro_nome: "Diogo",
    sobrenome: "Alves",
    data_nascimento: "2008-01-15",
    sexo: "masculino",
  },
  {
    id_residente: 5,
    primeiro_nome: "Elisa",
    sobrenome: "Fernandes",
    data_nascimento: "2003-05-30",
    sexo: "feminino",
  },
  {
    id_residente: 6,
    primeiro_nome: "Fábio",
    sobrenome: "Gomes",
    data_nascimento: "2001-09-05",
    sexo: "masculino",
  },
  {
    id_residente: 7,
    primeiro_nome: "Gabriela",
    sobrenome: "Lima",
    data_nascimento: "2006-02-12",
    sexo: "feminino",
  },
  {
    id_residente: 8,
    primeiro_nome: "Hugo",
    sobrenome: "Nunes",
    data_nascimento: "2000-12-25",
    sexo: "masculino",
  },
  {
    id_residente: 9,
    primeiro_nome: "Isabela",
    sobrenome: "Ribeiro",
    data_nascimento: "2007-08-19",
    sexo: "feminino",
  },
  {
    id_residente: 10,
    primeiro_nome: "João",
    sobrenome: "Santos",
    data_nascimento: "2004-04-03",
    sexo: "masculino",
  },
];

const mockFuncionarios = [
  {
    id_funcionario: 101,
    numero_registro: "A101",
    primeiro_nome: "Marcos",
    sobrenome: "Oliveira",
    turno: "manha",
    status: "ativo",
  },
  {
    id_funcionario: 102,
    numero_registro: "A102",
    primeiro_nome: "Lúcia",
    sobrenome: "Pereira",
    turno: "tarde",
    status: "ativo",
  },
  {
    id_funcionario: 103,
    numero_registro: "A103",
    primeiro_nome: "Ricardo",
    sobrenome: "Abreu",
    turno: "noite",
    status: "ativo",
  },
  {
    id_funcionario: 104,
    numero_registro: "B101",
    primeiro_nome: "Sofia",
    sobrenome: "Martins",
    turno: "manha",
    status: "inativo",
  },
  {
    id_funcionario: 105,
    numero_registro: "B102",
    primeiro_nome: "Tiago",
    sobrenome: "Cardoso",
    turno: "tarde",
    status: "ativo",
  },
  {
    id_funcionario: 106,
    numero_registro: "B103",
    primeiro_nome: "Vanessa",
    sobrenome: "Rocha",
    turno: "noite",
    status: "ativo",
  },
  {
    id_funcionario: 107,
    numero_registro: "C101",
    primeiro_nome: "André",
    sobrenome: "Barbosa",
    turno: "manha",
    status: "ativo",
  },
  {
    id_funcionario: 108,
    numero_registro: "C102",
    primeiro_nome: "Beatriz",
    sobrenome: "Freitas",
    turno: "tarde",
    status: "ativo",
  },
  {
    id_funcionario: 109,
    numero_registro: "C103",
    primeiro_nome: "Cauã",
    sobrenome: "Dias",
    turno: "noite",
    status: "inativo",
  },
  {
    id_funcionario: 110,
    numero_registro: "D101",
    primeiro_nome: "Daniela",
    sobrenome: "Pinto",
    turno: "manha",
    status: "ativo",
  },
];

const mockMedicamentos = [
  {
    id: 1,
    horario: "08:00",
    residenteNome: "Ana Silva",
    medicamento: "Paracetamol",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 2,
    horario: "08:00",
    residenteNome: "Bruno Costa",
    medicamento: "Dipirona",
    dosagem: "20 gotas",
    tipo: "Gotas",
  },
  {
    id: 3,
    horario: "09:00",
    residenteNome: "Carla Mendes",
    medicamento: "Amoxicilina",
    dosagem: "5ml",
    tipo: "Líquido",
  },
  {
    id: 4,
    horario: "10:00",
    residenteNome: "Diogo Alves",
    medicamento: "Ibuprofeno",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 5,
    horario: "12:00",
    residenteNome: "Elisa Fernandes",
    medicamento: "Loratadina",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 6,
    horario: "14:00",
    residenteNome: "Fábio Gomes",
    medicamento: "Dipirona",
    dosagem: "20 gotas",
    tipo: "Gotas",
  },
  {
    id: 7,
    horario: "16:00",
    residenteNome: "Gabriela Lima",
    medicamento: "Paracetamol",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 8,
    horario: "18:00",
    residenteNome: "Hugo Nunes",
    medicamento: "Omeprazol",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
  {
    id: 9,
    horario: "20:00",
    residenteNome: "Isabela Ribeiro",
    medicamento: "Amoxicilina",
    dosagem: "5ml",
    tipo: "Líquido",
  },
  {
    id: 10,
    horario: "22:00",
    residenteNome: "João Santos",
    medicamento: "Ibuprofeno",
    dosagem: "1 comp.",
    tipo: "Comprimido",
  },
];

const mockAtividades = [
  {
    id: 1,
    data: "2025-11-16T10:00:00Z",
    horario: "10:00:00",
    nome_atividade: "Pintura em Tela",
    duracao: "1 hora",
    status: "Agendada",
    participantes_nomes: "Ana Silva, Bruno Costa",
  },
  {
    id: 2,
    data: "2025-11-16T15:00:00Z",
    horario: "15:00:00",
    nome_atividade: "Fisioterapia em Grupo",
    duracao: "45 minutos",
    status: "Agendada",
    participantes_nomes: "Carla Mendes, Diogo Alves",
  },
  {
    id: 3,
    data: "2025-11-17T09:00:00Z",
    horario: "09:00:00",
    nome_atividade: "Aula de Música",
    duracao: "1 hora",
    status: "Agendada",
    participantes_nomes: "Elisa Fernandes, Fábio Gomes",
  },
  {
    id: 4,
    data: "2025-11-17T14:00:00Z",
    horario: "14:00:00",
    nome_atividade: "Leitura Coletiva",
    duracao: "1 hora",
    status: "Concluída",
    participantes_nomes: "Gabriela Lima",
  },
  {
    id: 5,
    data: "2025-11-18T10:00:00Z",
    horario: "10:00:00",
    nome_atividade: "Jardinagem",
    duracao: "1 hora",
    status: "Agendada",
    participantes_nomes: "Hugo Nunes, Isabela Ribeiro",
  },
  {
    id: 6,
    data: "2025-11-18T16:00:00Z",
    horario: "16:00:00",
    nome_atividade: "Sessão de Cinema",
    duracao: "2 horas",
    status: "Agendada",
    participantes_nomes: "João Santos, Ana Silva",
  },
  {
    id: 7,
    data: "2025-11-19T11:00:00Z",
    horario: "11:00:00",
    nome_atividade: "Alongamento",
    duracao: "30 minutos",
    status: "Cancelada",
    participantes_nomes: "Bruno Costa",
  },
  {
    id: 8,
    data: "2025-11-19T15:00:00Z",
    horario: "15:00:00",
    nome_atividade: "Oficina de Culinária",
    duracao: "1 hora",
    status: "Agendada",
    participantes_nomes: "Carla Mendes, Elisa Fernandes",
  },
  {
    id: 9,
    data: "2025-11-20T09:00:00Z",
    horario: "09:00:00",
    nome_atividade: "Jogo de Tabuleiro",
    duracao: "1 hora",
    status: "Agendada",
    participantes_nomes: "Diogo Alves, Fábio Gomes",
  },
  {
    id: 10,
    data: "2025-11-20T14:00:00Z",
    horario: "14:00:00",
    nome_atividade: "Conversa Terapêutica",
    duracao: "1 hora",
    status: "Agendada",
    participantes_nomes: "Gabriela Lima, Hugo Nunes",
  },
];

const mockRelatorios = [
  {
    id: 1,
    data: "2025-11-16T00:00:00Z",
    residenteNome: "Ana Silva",
    medicamento: "Paracetamol",
    responsavelNome: "Marcos Oliveira",
    statusMedicacao: "Medicado",
  },
  {
    id: 2,
    data: "2025-11-16T00:00:00Z",
    residenteNome: "Bruno Costa",
    medicamento: "Dipirona",
    responsavelNome: "Lúcia Pereira",
    statusMedicacao: "Medicado",
  },
  {
    id: 3,
    data: "2025-11-15T00:00:00Z",
    residenteNome: "Carla Mendes",
    medicamento: "Amoxicilina",
    responsavelNome: "Ricardo Abreu",
    statusMedicacao: "Não Tomado",
  },
  {
    id: 4,
    data: "2025-11-15T00:00:00Z",
    residenteNome: "Diogo Alves",
    medicamento: "Ibuprofeno",
    responsavelNome: "Sofia Martins",
    statusMedicacao: "Medicado",
  },
  {
    id: 5,
    data: "2025-11-14T00:00:00Z",
    residenteNome: "Elisa Fernandes",
    medicamento: "Loratadina",
    responsavelNome: "Tiago Cardoso",
    statusMedicacao: "Medicado",
  },
  {
    id: 6,
    data: "2025-11-14T00:00:00Z",
    residenteNome: "Fábio Gomes",
    medicamento: "Dipirona",
    responsavelNome: "Vanessa Rocha",
    statusMedicacao: "N/A",
  },
  {
    id: 7,
    data: "2025-11-13T00:00:00Z",
    residenteNome: "Gabriela Lima",
    medicamento: "Paracetamol",
    responsavelNome: "André Barbosa",
    statusMedicacao: "Medicado",
  },
  {
    id: 8,
    data: "2025-11-13T00:00:00Z",
    residenteNome: "Hugo Nunes",
    medicamento: "Omeprazol",
    responsavelNome: "Beatriz Freitas",
    statusMedicacao: "Medicado",
  },
  {
    id: 9,
    data: "2025-11-12T00:00:00Z",
    residenteNome: "Isabela Ribeiro",
    medicamento: "Amoxicilina",
    responsavelNome: "Cauã Dias",
    statusMedicacao: "Medicado",
  },
  {
    id: 10,
    data: "2025-11-12T00:00:00Z",
    residenteNome: "João Santos",
    medicamento: "Ibuprofeno",
    responsavelNome: "Daniela Pinto",
    statusMedicacao: "Não Tomado",
  },
];
